//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusDBWebApplication.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buses
    {
        public Buses()
        {
            this.Services = new HashSet<Services>();
        }
    
        public int bus_id { get; set; }
        public string brand { get; set; }
        public int number_of_seats { get; set; }
    
        public virtual ICollection<Services> Services { get; set; }
    }
}
