//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusDBWebApplication.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cities
    {
        public Cities()
        {
            this.Froms = new HashSet<Routes>();
            this.Wheres = new HashSet<Routes>();
        }
    
        public int city_id { get; set; }
        public string title { get; set; }
    
        public virtual ICollection<Routes> Froms { get; set; }
        public virtual ICollection<Routes> Wheres { get; set; }
    }
}
