//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusDBWebApplication.DataBase
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Passengers
    {
        public Passengers()
        {
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int passenger_id { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string patronymic { get; set; }
        public string inicial { get { return String.Format("{0} {1} {2} паспорт: серия-{3} номер-{4}",surname,name, patronymic,passport_number,passport_series); } 
            set { inicial = value; } 
        } 
        [MaxLength(4)]
        [Range(0, int.MaxValue, ErrorMessage = "Пожалуйста, введите число")]
        public string passport_series { get; set; }
        [MaxLength(6)]
        [Range(0, int.MaxValue, ErrorMessage = "Пожалуйста, введите число")]
        public string passport_number { get; set; }
    
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
