//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusDBWebApplication.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Routes
    {
        public Routes()
        {
            this.Services = new HashSet<Services>();
        }
    
        public int route_id { get; set; }
        public int from { get; set; }
        public int where { get; set; }
        public string way { get { return String.Format("{0}-{1}", FromWhence.title, WhereAbouts.title); } set { way = value; } }
    
        public virtual Cities FromWhence { get; set; }
        public virtual Cities WhereAbouts { get; set; }
        public virtual ICollection<Services> Services { get; set; }
    }
}
