//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusDBWebApplication.DataBase
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
    
    public partial class Services
    {
        public Services()
        {
            this.Tickets = new HashSet<Tickets>();
            this.Buses = new HashSet<Buses>();
        }
    
        public int service_id { get; set; }
        public int route_id { get; set; }
        public int from { get; set; }
        public int where { get; set; }
        public int number_of_free_seats
        {
            get
            {
                int allSeats = 0;
                foreach (Buses bus in Buses)
                {
                    allSeats += bus.number_of_seats;
                }
                return allSeats - Tickets.Count;
            }
        }
        public int service_number { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm}", ApplyFormatInEditMode = true)]
        public System.DateTime departure_time { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm}", ApplyFormatInEditMode = true)]
        public System.DateTime arrival_time { get; set; }
    
        public virtual Routes Routes { get; set; }
        public virtual ICollection<Tickets> Tickets { get; set; }
        public virtual ICollection<Buses> Buses { get; set; }
    }
}
