//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusDBWebApplication.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int ticket_id { get; set; }
        public int service_id { get; set; }
        public int route_id { get; set; }
        public int from { get; set; }
        public int where { get; set; }
        public int passenger_id { get; set; }
        public System.DateTime purchase_date { get; set; }
    
        public virtual Passengers Passengers { get; set; }
        public virtual Services Services { get; set; }
    }
}
